//%attributes = {"invisible":true}

C_BOOLEAN:C305(<>IP_INITED_B)
C_LONGINT:C283(<>WS_PSSID)
C_TEXT:C284(<>SC_EVERYBODY_T)
C_TEXT:C284(<>SC_NOBODY_T)
C_DATE:C307(<>DB_DATE)
C_TEXT:C284(<>DB_VERSION)
C_TEXT:C284(<>WS_WINDOWTITLE_T)
C_TEXT:C284(<>REFGROUPSMENU)
C_TEXT:C284(<>REFSCHEMASMENU)
C_TEXT:C284(<>DEFAULTSCHEMANAME_T)
C_LONGINT:C283(<>SC_VERSION_OK_L)